### PR TITLE
Media limit update

### PR DESCRIPTION
**Pull request by TrixyMixy**
Added a guild warn logging feature which also records the number of times a user has bypassed the limit (hopefully I can't really test.)

### CODE REVIEW

**Comment by Khaomi** [comment]
i dont think we need auto translate

**Comment by Khaomi** [comment]
also, make a new branch, the git history is fucked

**Comment by TrixyMixy** [comment]
I feel that auto translate would very much benefit moderation and users ability to interact with people speaking various languages.

**Comment by TrixyMixy** [comment]
Also creating a new branch isn't fixing the history, I think only creating a new repo would get rid of those weird ghost commits.

**Comment by Khaomi** [comment]
Alright, YOu can delete the current branch, and make a new one, don't forget to copy the folder n stuff

**Pull request closed without merging**
